### ISSUE TITLE
How to build in vscode

### ISSUE THREAD

**Issue by wx4cb** [rppicomidi/pico-embedded-cli#1]
i'm used to using micropython to build things for my pico, but i thought  would give vscode a try.

im new to vscode, do you have any build instructions for building and sending to a pico using vscode ?

**Comment by rppicomidi** [comment]
@wx4cb Forgive me if you have already done this, but have you built any Raspberry Pi Pico code using VS Code? If not, please refer to the [Getting Started Guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf). See especially Chapter 7 and if your build host is not a Raspberry Pi, see Chapter 9. Once you have the basic  Hello USB project working, it means your environment is set up correctly to build and debug Pico projects using VS Code.

To build this project, in VS Code, use the File->Open Folder... command to open the directory where you cloned this project. There is already a `.vscode` directory set up. The same build and run procedures work as they do in the Hello USB project.

Please let me know if you get it working or need more help.

**Comment by wx4cb** [comment]
To be honest, no I'm new to vscode and vs in general. I'm an old school
vi/cli user, but was going to try it out.

I also haven't had the time to dig into it more as I've been out of town
for work until today. Hopefully soon I'll have more time to play.

I'll let you know

**Comment by rppicomidi** [comment]
@wx4cb It has been more than a month. I am going to close this issue. If, after you have gotten the examples from the getting started guide working, you still need help with this project, please reopen this issue.
